### ISSUE TITLE
Get data from attribute

### ISSUE THREAD

**Issue by srumelhart** [Hugovdberg/PIconnect#395]
* PIconnect version: .0.7.0
* Python version: 2.7.13
* Operating System: Windows Server 2016

### Description

I am trying to get values from an attribute of an element similar to how I am getting values from a PI tag. My PI tag example is this (retrieves data at 5 minute intervals for the previous day):

```python
import PIconnect as PI
import pandas as pd
from datetime import datetime
from datetime import timedelta

end = datetime.today()
start = (end + timedelta(days=-1)).date()
end = end.strftime('%m-%d-%Y')
start = start.strftime('%m-%d-%Y')
interval = '5m'

with PI.PIServer() as server:
    tags = server.search('BLK1WNAC*MVWdspd')
    output = pd.concat([tag.interpolated_values(start, end, interval) for tag in tags], axis = 1)
output.to_csv("D:\Python\Windspeed\\Windspeed " + start + ".csv")
```

### What I Did

I have been able to retrieve the names of the attributes of an element in my current PI system:

```python
import PIconnect as PI

with PI.PIAFDatabase() as database:
	element = database.descendant(r'MNRCSRVR01 ModuleDB\Turbine\A04')
	for attribute in element.attributes:
		print (attribute)
```

Output:

ExpectedProduction_Met2
StateFault_Text
Met1_WdSpd
Turbine_Name
OperationState_Text
Turbine_Tag_Name
OperationState
WindSpeed
ExpectedProduction_Met1
ExpectedProduction_Met3
MetAvg_WdSpd
SCADAState_Text
TurbineCondition
SCADAState
WTGState_Text
Met3_WdSpd
VoltagePhaseB_LN
ActivePower
AvailabilitySCADA
StateFault
ExpectedProduction_Nac
Turbine_Num
WTGState
Met2_WdSpd

How do I get the 5 minute data for one of the attributes (such as ExpectedProduction_Nac)?

Attached is the screen in PI System Explorer that shows the attributes.

![PI System Explorer](https://user-images.githubusercontent.com/50027457/57311952-db261200-70a9-11e9-8415-0ce2196abedc.png)

**Comment by Hugovdberg** [comment]
I beg you pardon for the late response. To extract data from PI AF attributes you can use the same `recorded_values` and `interpolated_values` as on PI Points. Because of the hierarchy of the PI AF database the way to access those attributes is a little different.

As you already found, you can iterate over the `PIAFElement.attributes`. This `attributes` is actually a dictionary of `PIAFAttribute` objects, and the default way to iterate over a dictionary returns its keys.

To get the data for `ExpectedProduction_Nac` you can use the following snippet:

```python
import PIconnect as PI

with PI.PIAFDatabase() as database:
	element = database.descendant(r'MNRCSRVR01 ModuleDB\Turbine\A04')
	expected_production = element.attributes['ExpectedProduction_Nac']
	data = expected_production.interpolated_values('01-01-2019', '*', '5m')
```

**Comment by Hugovdberg** [comment]
I just updated the documentation, I hope it helps in further understanding what went wrong in your first try: https://piconnect.readthedocs.io/en/latest/tutorials/piaf.html
