### ISSUE TITLE
Cannot Import PIconnect as PI

### ISSUE THREAD

**Issue by kowdykung** [Hugovdberg/PIconnect#496]
When I import `Import PIconnect as PI` I got this error. Do I need to setup OSIsoft?

`AttributeError                            Traceback (most recent call last)
<ipython-input-7-fb52c6977076> in <module>
----> 1 import PIconnect as PI
      2 print(list(PI.PIServer.servers.keys()))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\PIconnect\__init__.py in <module>
     24 from PIconnect.AFSDK import AF
     25 from PIconnect.PI import PIServer
---> 26 from PIconnect.PIAF import PIAFDatabase
     27 
     28 __version__ = "0.7.1"

~\AppData\Local\Continuum\anaconda3\lib\site-packages\PIconnect\PIAF.py in <module>
     59 
     60 
---> 61 class PIAFDatabase(object):
     62     """Context manager for connections to the PI Asset Framework database."""
     63 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\PIconnect\PIAF.py in PIAFDatabase()
     65 
     66     servers = {x.Name: {"server": x, "databases": {}} for x in AF.PISystems()}
---> 67     default_server = servers[AF.PISystems().DefaultPISystem.Name]
     68 
     69     def __init__(self, server=None, database=None):

AttributeError: 'NoneType' object has no attribute 'Name'`

**Comment by Hugovdberg** [comment]
Thanks for reporting this, I never considered that some configurations might not have a DefaultPISystem set. This is definitely a bug that should be easy to fix.

**Comment by Hugovdberg** [comment]
I added a fix that should fix the issue, could you please try and install this test version using `pip install git+https://github.com/Hugovdberg/PIconnect@feature/496_default_pisystem`?

**Comment by mpepera** [comment]
I had a slightly different error. We are using an older PI Server without an Asset Framework implementation. Import PIconnect failed on the PIAF import database step. I just commented out the following line from __init__.py and happily went along my way!

`from PIconnect.PIAF import PIAFDatabase`

Cool project! Thanks for building it.

```
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3_32\lib\site-packages\PIconnect\__init__.py", line 26, in <module>
    from PIconnect.PIAF import PIAFDatabase

  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3_32\lib\site-packages\PIconnect\PIAF.py", line 61, in <module>
    class PIAFDatabase(object):

  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3_32\lib\site-packages\PIconnect\PIAF.py", line 67, in PIAFDatabase
    default_server = servers[AF.PISystems().DefaultPISystem.Name]

AttributeError: 'NoneType' object has no attribute 'Name'
```
