### ISSUE TITLE
Unable to Configure Timezone

### ISSUE THREAD

**Issue by jbshiau235** [Hugovdberg/PIconnect#504]
I tried out the print(PI.PIConfig.DEFAULT_TIMEZONE) after importing PIconnect as PI, but it didn't recognize PIConfig as an attribute of PI. Is there something I'm missing or a different way to specify time zone for PI?

![image](https://user-images.githubusercontent.com/3252618/72906514-f8fadc00-3cf7-11ea-9559-0ac67198a6e6.png)

**Comment by Hugovdberg** [comment]
This should work in the latest development version (not on PyPI yet): you can install it using `pip install git+https://github.com/Hugovdberg/PIconnect@develop` (see https://github.com/Hugovdberg/PIconnect/issues/499#issuecomment-570555034). Does that work for you?

**Comment by jbshiau235** [comment]
Ah yes it works now thanks! Is there documentation somewhere on how the timezone should be formatted as when assigning it to the DEFAULT_TIMEZONE attribute? I want to make mine UTC -6 or Central Standard Time in the US.

**Comment by jbshiau235** [comment]
Issue resolved. Used pytz formatting per documentation. Thanks!
