### ISSUE TITLE
Connect to PI server using credentials

### ISSUE THREAD

**Issue by gygabyte017** [Hugovdberg/PIconnect#511]
Hi, I didn't get how to explicitly pass username and password when connecting to a specific PI server. In my environment I need to provide a technical user to connect to the server instead of using my own Windows credentials.

**Comment by Hugovdberg** [comment]
Currently this isn't supported in the python API, and I think I cannot test it locally. Would you be able to test it if I added it to the code?

**Comment by gygabyte017** [comment]
Sure, I can test it against several PI servers with different
configurations / environments.
Just tell me what to do.

Thank you,
Regards

Il mar 3 mar 2020, 08:59 Hugo Lapré <notifications@github.com> ha scritto:

**Comment by Hugovdberg** [comment]
Can you install the test version using `pip install git+https://github.com/Hugovdberg/PIconnect@feature/511_connection_credentials`?

You should then be able to connect to the PI Data Archive using something like the following:
```python
import PIconnect as PI
from PIconnect.PIConsts import AuthenticationMode

with PI.PIServer(username='...', password='...', authentication_mode=AuthenticationMode.PI_USER_AUTHENTICATION) as server:
    points = server.search('*')
    print(len(points))
```

Note that it's required to provide both a username and password (no default username). If you need to provide a login domain you can use the argument `domain`. If you need Windows authentication instead of PI user authentication you should set the `authentication_mode` to `AuthenticationMode.WINDOWS_AUTHENTICATION`.

If you experience any issues please let me know!

**Comment by gygabyte017** [comment]
Thank you! Here's my results.

SecureString object seems not to be working: I get PIAuthenticationException.

Something seems wrong because if I print the SecurePassword.Length I get 0, so I guess no password is being passed to the server:
```
    def __enter__(self):
        if self._credentials:
            print(self.server_name)
            print(self._credentials[0].SecurePassword.Length)
            self.connection.Connect(*self._credentials)
            print(self.connection.CurrentUserName)
```

Instead, if I replace the SecureString with just a String:

```
cred = [username, password] + ([domain] if domain else [])
```

the connection is successful (I added some print to the `__enter__` method to get sure that the correct server and the correct user is will logged in).

**Comment by gygabyte017** [comment]
This works with SecureString:

```
        if username:
            from System.Net import NetworkCredential
            from System.Security import SecureString
            
            secureString = SecureString()
            for c in password:
                secureString.AppendChar(c)

            cred = [username, secureString] + ([domain] if domain else [])
            self._credentials = (NetworkCredential(*cred), int(authentication_mode))
```

I guess a SecureString in .NET cannot be constructed from a string, but must be built char by char...

**Comment by Hugovdberg** [comment]
Thanks for testing! I will fix the `SecureString` construction, that has some more guarantees the text is removed from memory as soon as possible.

**Comment by Hugovdberg** [comment]
I pushed a new version that incorporates the correct construction of the `SecureString`, could you please update using the same command I previously sent?

**Comment by gygabyte017** [comment]
It works great! I tested with both `AuthenticationMode`s and different domains/credentials, it works in every test.

I believe the issue is solved and can be committed to master, if you agree this can be closed.

Thank you again,
Regards

**Comment by Hugovdberg** [comment]
Great to hear that! I will include it in the development release for now, it will trickle into master in the next release.

**Comment by panshu77** [comment]
thanks for adding this new function. Just wonder when the new release with this function will come out. And if not soon, is the test version still available? thanks.

**Comment by fouadsel88** [comment]
Thank you for fix that, is the new release coming soon? I am getting the same issue and I would like to use AuthenticationMode.WINDOWS_AUTHENTICATION to my script.

**Comment by Hugovdberg** [comment]
you can always install from the github development branch, but I'll try to make a new release soon.

To install the latest developments you can install using: `pip install --upgrade git+https://github.com/Hugovdberg/PIconnect@develop`

**Comment by mhernandez1005** [comment]
Hello, is it possible to connect to PI database over VPN? I receive PIAuthenticationException when trying to connect to pi database. The PIconnect version is 0.9.1, with the updated secure string. Thank you,
