### ISSUE TITLE
ToDo Line 15: Remove auxiliary classes 

### ISSUE THREAD

**Issue by Cazforshort** [Hugovdberg/PIconnect#520]
Feature request
===============

Remove classes such as AFEnumerationValue
--------

One of the things on your ToDo doc is to get rid of the auxiliary classes. Is there a way to do this manually? When I try to convert the type of one of the series to floats it just gives an error.

data.D1.astype(float)
TypeError: float() argument must be a string or a number, not 'AFEnumerationValue'

Motivation and summary
----------------------

Need a method for using the data from the PI pulls

Suggested solution
------------------

I noticed that it is possible to first convert the data (floats, strings, ect) into strings only. After that the numbers can all be converted into floats. From there I think I can fix the dataframe completely. Maybe there is an easier way. 

Rejected options
----------------

Additional context
------------------

**Comment by Hugovdberg** [comment]
Another way is to use `pd.to_numeric(data, errors='coerce')`, this will convert all non-numeric values to `NaN`. I'd rather not change this because there might be good reasons to keep the enumeration values, and some series might perhaps contain only non-numeric values. I often apply some pattern like this:

```python
with PI.PIServer() as server:
    point = server.search('*')[0]
    data = point.recorded_values('-7d', '*')
    data = data.to_frame()
    data['values'] = pd.to_numeric(data[point.tag], errors='coerce')
    data.loc[data['values'].isna(), 'messages'] = data.loc[data['values'].isna(), point.tag].apply(str)
```
