### ISSUE TITLE
Returned Column Name for Summarized Data

### ISSUE THREAD

**Issue by mburch77** [Hugovdberg/PIconnect#533]
Hello Hugo,

Thank you for putting this package together, it has been very useful for pulling PI data. 

Currently when using PIPoint.summaries, the returned pandas dataframe has the summary name as the column name. However when pulling summaries for several PI tags at once, all columns will have the summary name as the column name. Could there be an option for summaries to return the PI tag as the column name instead of the summary name, like with interpolated_values?

An example of the issue I am having is below:
![Issue](https://user-images.githubusercontent.com/67473934/85873785-9ecadf00-b79f-11ea-97e9-e978372f34c0.PNG)

**Comment by Hugovdberg** [comment]
I think you are looping over a list op PIPoints and then concatenating them to a single dataframe right? The reason the summary name is reported, is that you can request multiple summary types at the same time. Returning the PI tag would result in duplicate column names from the initial call. It might be interesting to return a multilevel column index, but I think this is more up to the user.

To fix your problem you could try the following:

```python
with PI.PIServer() as server:
    points = server.search('*')
    data = []
    for point in points:
        tmp = point.summaries('-2d', '*', '5m', summary_types=SummaryTypes.AVERAGE)
        tmp.rename(columns={'AVERAGE': point.tag})
        data.append(tmp)
    data = pd.concat(data, axis=1)
```

**Comment by mburch77** [comment]
Thanks for this solution Hugo. 

I just had to add `inplace=True` to `tmp.rename(columns={'AVERAGE': point.tag})` for the code to work.
