### ISSUE TITLE
Some thoughts on PIConnect

### ISSUE THREAD

**Issue by inselbuch** [Hugovdberg/PIconnect#538]
Well it's pretty terrific that you have put this together. And I have tested it and it works. Here's a thought:

We have a dozen PI/AF servers configured. But some of them are not available. When we want to connect to a specific server, PIConnect seems to try to validate all the servers in the list. And since we don't have access to some of the servers at all times, we get a timeout.

Feel free to contact me on e-mail inselbuch@gmail.com

Thanks for this effort!

**Comment by negodfre** [comment]
Yeah, I have this same issue. 
I made a fork where if it fails to connect it prints out the server that failed to connect & keeps going.

**Comment by AlcibiadesCleinias** [comment]
sorry for interfering, I merely want to leave a link on the pr: https://github.com/Hugovdberg/PIconnect/pull/562
