### ISSUE TITLE
pandas assertion error

### ISSUE THREAD

**Issue by somuchung** [Hugovdberg/PIconnect#553]
Hi! Thanks for this awesome package!!

Below is my system info:

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17763 N/A Build 17763
Python 3.7.6

Here's my code that works for example:

with PI.PIServer() as server:
    points=server.search('tagname')
    data=points[0].recorded_values('*-89h','*')
    print(data)

but if enter -90h or larger for the start time, it throws a pandas assertion error

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-278-6d2252389da9> in <module>
      2     points=server.search('TO00742510-Sump_Temperature_Transmitter')
      3     data=points[0].recorded_values('*-90h','*')
----> 4     print(data)

~\Anaconda3\lib\site-packages\pandas\core\series.py in __repr__(self)
   1369             min_rows=min_rows,
   1370             max_rows=max_rows,
-> 1371             length=show_dimensions,
   1372         )
   1373         result = buf.getvalue()

~\Anaconda3\lib\site-packages\pandas\core\series.py in to_string(self, buf, na_rep, float_format, header, index, length, dtype, name, max_rows, min_rows)
   1433             float_format=float_format,
   1434             min_rows=min_rows,
-> 1435             max_rows=max_rows,
   1436         )
   1437         result = formatter.to_string()

~\Anaconda3\lib\site-packages\pandas\io\formats\format.py in __init__(self, series, buf, length, header, index, na_rep, name, float_format, dtype, max_rows, min_rows)
    258         self.adj = _get_adjustment()
    259 
--> 260         self._chk_truncate()
    261 
    262     def _chk_truncate(self) -> None:

~\Anaconda3\lib\site-packages\pandas\io\formats\format.py in _chk_truncate(self)
    283                 row_num = max_rows // 2
    284                 series = series._ensure_type(
--> 285                     concat((series.iloc[:row_num], series.iloc[-row_num:]))
    286                 )
    287             self.tr_row_num = row_num

~\Anaconda3\lib\site-packages\pandas\core\base.py in _ensure_type(self, obj)
     91         Used by type checkers.
     92         """
---> 93         assert isinstance(obj, type(self)), type(obj)
     94         return obj
     95 

AssertionError: <class 'pandas.core.series.Series'>

Pleas advise

**Comment by Hugovdberg** [comment]
Sorry for not replying, I think this isn't really a `PIconnect` error but more of a `pandas` error. Apparently you can donwload the data just fine, but when printing the data `pandas` trips over some value. If it happens again, could you try printing `data.head()` to get only the first values that apparently make `pandas` cause an error? I suspect there was some sort of error code in the Series that `pandas` did not know how to format when cutting the series into chunks for abbreviation, but that's a wild guess. If it happens again feel free to reopen.

**Comment by somuchung** [comment]
Thanks for the reply. For unrelated reasons I had to rebuild my anaconda environment. after that it worked with no issues.
