### ISSUE TITLE
filtered_summaries does not appear to apply filter_expression arguement

### ISSUE THREAD

**Issue by georgc601** [Hugovdberg/PIconnect#584]
Bug report
==========

Description
-----------

When attempting to use a filter_expression argument with the filtered_summaries method, the method does not appear to be applying the argument, or it does not appear to be applying the arguement consistently. 

To Reproduce
------------

1.  Assign a PIPoint to a variable called point.
2.  Run: point.filtered_summaries('6/1/2021', '*', '120d', filter_expression = "'%tag%' < 500", summary_types=8)
     In this case, this PIPoint has some data anomalies I want to filter out, and I only want the single maximum value below the 
     filtered value (hence the long time interval).
4.  See errors in screenshots

Expected behavior
-----------------

I expected that the single maximum value returned would be below 500, but instead, I continue to get a value above 500.

Possible solutions
------------------

I have confirmed that recored_values and interpolated_values methods both apply the filter_expression argument correctly, in a manner that I expect and when following the examples provided in the documentation. 

So I am wondering if there is a bug in the code for filtered_summaries (but maybe just for filtering greater than?) or maybe I just have a syntax issue.

Screenshots
-----------
Snap trying to find the single max value over the time period, but it's not filtering.
![image](https://user-images.githubusercontent.com/70650608/127365521-67e41de0-a2e0-421d-8bd3-13f30eff359d.png)

Snap trying to find the max value below 400 every 5 days, but there are a bunch of them above 400
![image](https://user-images.githubusercontent.com/70650608/127365994-6e6fb914-9a10-4418-b3a8-846d0a4a25d7.png)

Snap showing that, oddly enough, filtering seems to work for values greater than
![image](https://user-images.githubusercontent.com/70650608/127366177-d9d87b91-dabb-4dff-b621-e8d621bf690e.png)

System
------

-   OS: Windows 10
-   Python version: Python 3.7
-   PIconnect version: 0.80

Additional context
------------------

I just wanted to thank you and the community for putting this together. Its already been so amazingly helpful to use python to gather PI data and manipulate it. Using Datalink was getting problematic as the data sets grew in size and the various asks.

**Comment by Hugovdberg** [comment]
First of all, glad to hear the package is useful to you! It is the exact same frustration with Datalink (and Excel in general) that lead to developing this wrapper around the SDK.

Regarding the issue you submitted, that is certainly some unexpected result. I did some tries myself, and I think this is related to how the `filter_expression` is applied by the PI Data Archive. `PIconnect` simply passes the expression to the SDK and assumes that knows how to handle it. I'm affraid I can't do much about this in the package itself. 

### _The following is mostly wild speculation!!_
As I said, I did poke around at this for a bit, and come to similar results and have a hunch what is going on in the background. The default setting for the server is to apply the filter to the recorded values within the interval and then summarise the data. However, I think the server also interpolates the data points to include the start and end of the interval as well. I suspect the filter is applied to the data within the interval only, so if there is a large spike just outside the interval window, the data inside the interval conforms to the filter, but then the values are interpolated to the edges, which then could be outside the filtered domain. If I set the `filter_evaluation` to `PIConsts.ExpressionSampleType.INTERVAL`, and the `filter_interval` to for example `5m`, the data is first interpolated to a point for every 5 minutes, and only then it is filtered. It appears to me that the results in that case are a bit more intuitive, but still lead to some close misses.

**Comment by georgc601** [comment]
This package so far has been so very useful. Parsing through thousands of PI tags and getting data is so much faster via PIConnect. Though this bug leaves me at a bit of a standstill. Thanks to you, and the other contributing. I wish I had the python skills to assist.

I work for an electric utility and need to constantly find peak values over periods of time, and need to filter out bad data points. Normally I would simply shift the time period I was examining to avoid the data spikes but always wanted to use the filtering instead. Oddly enough, I have issues with it working in Datalink as well, so it makes sense that since PIConnect simply passes the expression to the SDK, that there is an error in the SDK.

Toying with what you mentioned above, setting `filter_evaluation` to `filter_evaluation=PI.PIConsts.ExpressionSampleType.INTERVAL` did not work for me, the spike remained (this spike for my data occurs within the time frame I am sampling from). However, once I used `calculation_basis = PI.PIConsts.CalculationBasis.EVENT_WEIGHTED` that did work and now it filters as I expected.
![image](https://user-images.githubusercontent.com/70650608/128039480-2337fcfd-c9fc-4c11-b1ba-21035157321a.png)

I need to understand more about the event weighting to apply it systematical with a script but at least it's something.

**Comment by Hugovdberg** [comment]
With event weighting each measurement has equal weighting in calculating statistics. With time weighting the time interval between two consecutive measurements is used as a weighting for each value. For calculating minima and maxima event weighting should be just fine for averages this could have weird effects if there are large spikes with relatively short intervals within your summary interval.

For validation of the results you could try to export some recorded values and then using `resample` on the pandas series calculate the statistics in python. These are event weighted (unless you find the time weighted function I posted on StackOverflow a while ago 😁).

**Comment by Hugovdberg** [comment]
Closing this issue as it appears to be counterintuitive behaviour of the underlying SDK but not something we can fix in the python package.
