### ISSUE TITLE
write to tag

### ISSUE THREAD

**Issue by sulla138** [Hugovdberg/PIconnect#592]
Hello, Hugo. Suppose there is a tag and we want to **WRITE** data to it. Could you please provide a sample Python code how to do it using your PIconnect package? Thank you.

**Comment by Hugovdberg** [comment]
At of the next release there will be a method to write values, which is already documented in the tutorials on [read the docs](https://piconnect.readthedocs.io/en/develop/tutorials/update_value.html). You can get the functionality by installing the development version from GitHub, or waiting a week or so until I get around to releasing version 0.9. Closing this issue for now as I don't think it will add new value. If you have specific issues with parts of the documentation then feel free to open a bug report!
