### ISSUE TITLE
PIconnect shows "Testing" after connect to PI servers

### ISSUE THREAD

**Issue by lujie11111** [Hugovdberg/PIconnect#595]
Bug report
==========

Description
-----------

`PIconnect` does not load the SDK correctly, but uses the Testing framework instead.

1.  Open python
2.  Run this snippet
```python
import PIconnect as PI

with PI.PIServer() as server:
    print(server.server_name)
```
3. result is "Testing" .... How to solve it? I am able to connect to my server in PI processbook

Expected behavior
-----------------

The name of the connected server is printed

Possible solutions
------------------

--

System
------

-   OS: Windows
-   Python version: 3.8.5
-   PIconnect version: 0.9.0

**Comment by lujie11111** [comment]
I double checked - 
Requirement already satisfied: pythonnet in c:\users\luj13\appdata\local\programs\python\python38\lib\site-packages (2.5.2)
Requirement already satisfied: pycparser in c:\users\luj13\appdata\local\programs\python\python38\lib\site-packages (from pythonnet) (2.20)

but still showing:
with PI.PIServer() as server:
    print(server.search)

output:  <bound method PIServer.search of PIServer(\\Testing)>

**Comment by lujie11111** [comment]
no warming shown up. and with - **OSIsoft(r) AF SDK Version: 2.10.8.440** as results

**Comment by lujie11111** [comment]
I added 

import PIconnect as PI
print(list(PI.PIServer.servers.keys()))

after your code, and shwon time out:

System.TimeoutException: The open operation did not complete within the allotted timeout of 00:04:59.9900115. The time allotted to this operation may have been a portion of a longer timeout.

Server stack trace:
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.ICommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ClientBase`1.System.ServiceModel.ICommunicationObject.Open(TimeSpan timeout)
   at OSIsoft.AF.Support.AFProxy.Reconnect(Boolean autoPrompt, AFConnectionProtocol protocol, String host, Int32 port, String accountName, 
TimeSpan timeout)

**Comment by Hugovdberg** [comment]
Then I have no idea why in your situation the testing framework is loaded. I would think that when you import `PIconnect` in that same session it runs exactly that code as I copied and pasted it from the sourcecode for version 0.9.0. Is the environment correctly activated in the setting where you got the error?

Regarding the timeout, it appears one of the configured servers could not be reached. There is a check for this situation that was hard to test, but apparently the check handles the wrong base type of exceptions. I will fix this in the hotfix I linked to this issue.

**Comment by Hugovdberg** [comment]
I just pushed a new version to PyPI, could you please update and try if the error is now gone?

**Comment by lujie11111** [comment]
Hi Hugo, the 0.9.1 version works!! Thank you so much!!

**Comment by strojank** [comment]
Hey @Hugovdberg  - I am not sure if this is the right place for the question, but is `PIconnect` expected to work on a Red Hat OS?
