### ISSUE TITLE
AttributeError: module 'PIconnect' has no attribute 'PIServer' or equivalent

### ISSUE THREAD

**Issue by DScardini91** [Hugovdberg/PIconnect#625]
### Description

------------
When trying to run a server listing test I got this error message:

**AttributeError: module 'PIconnect' has no attribute 'PIServer'**

At first I was sure that the reason was some faulty installation, but after some alternative installs it became clear that this was not the root cause.

After digging a little deeper, I compared the AFSDK.py file with another library I have been using to get PI data, and found out that the path to AF SDK was set to 64-bit installations.

`

    PIAF_SDK = os.getenv("PIHOME", "C:\\Program Files\\PIPC")

    PIAF_SDK += "\\AF\\PublicAssemblies\\4.0\\"

    if not os.path.isdir(PIAF_SDK):

        raise ImportError("PIAF SDK not found in %s, check installation" % PIAF_SDK)
`
I changed this line to 

`PIAF_SDK = os.getenv("PIHOME", "C:\\Program Files(x86)\\PIPC")`

**And now it works like a charm.** 

### **Possible solutions**
--------------------
My company has lots of old desktops still, so by default any installation comes as 32-bit. 

My suggestion is a simple fix that can help other guys with jurassic 32-bit versions like myself, with some path flexibility depending on the version installed.

**Awesome work , thank you for doing this!**

**Comment by Hugovdberg** [comment]
You can actually just set an environment variable PIHOME to `C:\Program
Files(x86)\PIPC` which will then automatically be detected by PIconnect.
That's the whole point of that line, just in case the variable isn't set it
falls back to the default x64 path. Given the majority of systems are 64
bit nowadays I'm reluctant to change the default to the 32 bit version. I
will update the documentation to make clear how the SDK is located.

**Comment by WickedPawn** [comment]
My PIPC is also the 32 bit version. Changed the AFSDK.py line to:

`PIAF_SDK = os.getenv("PIHOME", "C:\\Program Files(x86)\\PIPC")`

And still get the error:  **module 'PIconnect' has no attribute 'PIServer'**

Any help will get me out of my misery.

**Comment by Hugovdberg** [comment]
This is fixed in the latest versions, as it now both checks `C:\Program Files\` and `C:\Program Files (x86)\`.
