### ISSUE TITLE
Trouble connecting to anything besides Testing

### ISSUE THREAD

**Issue by cchgray** [Hugovdberg/PIconnect#646]
Bug report
I cannot connect to anything besides a Testing Server

This seems similar to the #595 question. I've tried following through those suggestions.

Note that this script is not on the actual node / server that the PI is on. It's on the same network though.
In order to get past the 
      raise ImportError("PIAF SDK not found in %s, check installation" % PIAF_SDK) 
on #595, I added the PIPC to my local Program Files

![image](https://user-images.githubusercontent.com/7439397/181630824-0071f375-ae52-461e-9041-d9a7d146cd4b.png)

-   OS: Windows 10 64 bit
-   Python version: \3.9
-   PIconnect version: \0.9.1
-   OSIsoft(r) AF SDK Version: 2.10.9.593

Thanks!

**Comment by Hugovdberg** [comment]
I released a new version on PyPI (working on it to get it on `conda-forge` as well), that should be more explicit in loading the SDK. It now checks both the configured path in `PIPC`, as well as the default locations in `C:\Progam Files` and `C:\Program Files (x86)`. I'm thinking of making breaking changes in a new release that allows you to configure the SDK location more flexibly.

**Comment by keemsub** [comment]
Then why can't import clr?

**Comment by Hugovdberg** [comment]
Are you sure the `pythonnet` package is correctly installed?

Op do 13 jul. 2023 14:00 schreef 김민섭 ***@***.***>:
