### ISSUE TITLE
Question - how are servers discovered?

### ISSUE THREAD

**Issue by nmduarte** [Hugovdberg/PIconnect#654]
Bug report
==========

Description
-----------

Apologies for the basic question, but I am new to the library and have not 100% clarity on how the servers are discovered.
Although I am able to ping my server, the server is not discovered with running the code snippet in the tutorials. If I provide the name of the server, the same happens - it is not found and I only get the the Testing server.

Is there any kind of network constrain that could cause this?

Appreciate the help in advance.

To Reproduce
------------

```
import PIconnect as PI
with PI.PIServer(server='MyServerName') as server:
    print(server.server_name)
```

Expected behavior
-----------------

I would expect to see `MyServerName`

Possible solutions
------------------

Not a clear understanding why this would happen. Can ping the server. A different colleague, on a different office, does indeed see the server as it is supposed to be, which leads me to think that this is a network question. I just don't understand how the discovery is done and based on what. Assuming that I can ping the server, I would expect that I would be able to connect to it, unless we are talking about a specific port that might/can be blocked.

System
------

-   OS: macOS
-   Python version: Python 3.9.5
-   PIconnect version: PIconnect==0.9.1

**Comment by Hugovdberg** [comment]
sorry for the late reply, the servers should be detected from the pi configuration automatically. However, there is still an annoying issue that when the SDK is not found, the `PIconnect` package assumes it is in testing mode and drops in a fake replacement. This has only one 'server', called Testing, which is the behaviour you observed. Do you have the OSISoft client software installed on your machine?

**Comment by Hugovdberg** [comment]
Also I just noticed that you run the code on MacOS. I think that that is actually a blocker for the usage of this package as it fully relies on the underlying .NET Framework 4.5 based SDK by OSIsoft. Last time I checked they still rely on certain Windows only protocols that are not available in the .NET Core APIs.
