### ISSUE TITLE
recorded_values: exists a limit for output

### ISSUE THREAD

**Issue by RoseDeSable** [Hugovdberg/PIconnect#737]
Hi,
 I'm reading out the values for AIPoints in intervals of 1 hour. In some outputs I see "..." within the sequence of the output lines. Exists a limit for lines ? If it is so, can i set it higher ? For example for numpy arrays such limits are set. The programmer can set it higher up to the by the system allowed maximum.

Best Regards
Rose

**Comment by Hugovdberg** [comment]
I think you are referring to the number of rows shown in a jupyter notebook? The data is a `pandas.Series` with some extra info, and therefore the number of displayed rows is controlled by pandas. See this page op the pandas documentation: https://pandas.pydata.org/docs/user_guide/options.html, I think you need `pd.options.max_rows`
