### ISSUE TITLE
PIAFServer search not working for AF element attributes of format "BaseElement|Attribute"

### ISSUE THREAD

**Issue by RowanHolborn** [Hugovdberg/PIconnect#778]
Bug report
==========

Description
-----------
When searching for an AF element attribute, the PIAFServer.search function does not cater for short attribute paths that look like: "BaseElement|Attribute". When passing a query with the above format, the search function returns an empty list. The search function does work for nested attributes of the format "BaseElement|Attribute|Attribute2"

There is a logical check for splitstring > 2 in the function. Only if this condition is met, does the attribute get appended to the list which is returned.

To Reproduce
------------
1.  Create a PIAFServer instance connected to a database.
2.  Call the PIAFServer.search() function and pass a query of the format "BaseElement|Attribute"
3.  Observe how the returned list is empty

Expected behavior
-----------------
The search function should return a list of PIAFAttributes specfically for attributes of the path format "BaseElement|Attribute"

Possible solutions
------------------
In line 173 of PIAF.py, un-indent the append operation to the attributeList

Screenshots
-----------
![PIconnect issue bug report (screenshot fix)](https://github.com/user-attachments/assets/2e4a5925-5645-4a8c-9b70-342e21036a47)

The image shows the suggested unindent to fix the bug in the PIAFServer.search function

System
------
- OS: Windows 10 Enterprise 22H2
- Python version: 3.9.13
- PIconnect version: 0.10.6

Additional context
------------------
None

**Comment by RowanHolborn** [comment]
Thanks for quick fix!

**Comment by Hugovdberg** [comment]
You're welcome, I just published a new release, it should be on PyPI in a few minutes, and on conda-forge in a few hours. Thanks for reporting this and the suggestion for the fix!

**Comment by RowanHolborn** [comment]
Amazing! Thanks for making the change so quickly. Happy to help where I can.
